global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pihole'
    static_configs:
      - targets: ['192.168.7.241:9617', '192.168.7.242:9617']

  - job_name: 'ai-watchdog'
    static_configs:
      - targets: ['ai-watchdog:5000']
