---
# Services Configuration - Clickable service buttons with status

- DNS Services:
    - Pi-hole Primary:
        icon: pihole.png
        href: http://{{HOMEPAGE_VAR_PIHOLE_PRIMARY_IP}}/admin
        description: Primary DNS Ad-Blocker
        server: pihole-primary
        container: pihole_primary
        widget:
          type: pihole
          url: http://{{HOMEPAGE_VAR_PIHOLE_PRIMARY_IP}}
          key: {{HOMEPAGE_VAR_PIHOLE_API_KEY}}
    
    - Pi-hole Secondary:
        icon: pihole.png
        href: http://{{HOMEPAGE_VAR_PIHOLE_SECONDARY_IP}}/admin
        description: Secondary DNS Ad-Blocker
        server: pihole-secondary
        container: pihole_secondary
        widget:
          type: pihole
          url: http://{{HOMEPAGE_VAR_PIHOLE_SECONDARY_IP}}
          key: {{HOMEPAGE_VAR_PIHOLE_API_KEY}}
    
    - Cloudflared DoH:
        icon: cloudflare.png
        href: https://developers.cloudflare.com/1.1.1.1/
        description: DNS-over-HTTPS Proxy
        server: cloudflared
        container: cloudflared

- Monitoring & Observability:
    - Grafana:
        icon: grafana.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:3000
        description: Metrics Visualization & Dashboards
        server: grafana
        container: grafana
        widget:
          type: grafana
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:3000
          username: {{HOMEPAGE_VAR_GRAFANA_USER}}
          password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
    
    - Prometheus:
        icon: prometheus.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:9090
        description: Metrics Collection & Storage
        server: prometheus
        container: prometheus
        widget:
          type: prometheus
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:9090
    
    - Netdata:
        icon: netdata.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:19999
        description: Real-time System Monitoring
        server: netdata
        container: netdata
        widget:
          type: netdata
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:19999

- Management & Security:
    - Uptime Kuma:
        icon: uptimekuma.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:3001
        description: Service Uptime Monitoring
        server: uptime-kuma
        container: uptime-kuma
        widget:
          type: uptimekuma
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:3001
          slug: {{HOMEPAGE_VAR_KUMA_SLUG}}
    
    - Portainer:
        icon: portainer.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:9000
        description: Docker Container Management
        server: portainer
        container: portainer
        widget:
          type: portainer
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:9000
          env: 1
          key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    
    - Trivy Security:
        icon: si-aqua
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8080
        description: Vulnerability Scanner
        server: trivy
        container: trivy-server

- System Status:
    - Docker:
        icon: docker.png
        server: local
        container: /
        widget:
          type: docker
          url: unix:///var/run/docker.sock
    
    - System Resources:
        icon: mdi-server
        widget:
          type: resources
          cpu: true
          memory: true
          disk: /
          uptime: true
