global:
  resolve_timeout: 5m

route:
  receiver: 'signal'
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h

receivers:
  - name: 'signal'
    webhook_configs:
      - url: 'http://signal-webhook-bridge:8080/v1/send'
        send_resolved: true
