version: '3.8'

services:
  pihole_primary:
    image: pihole/pihole:latest
    container_name: pihole_primary
    environment:
      - TZ=Europe/London
      - WEBPASSWORD=admin
    networks:
      pihole_net:
        ipv4_address: 192.168.8.241
    restart: unless-stopped
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80'

  pihole_secondary:
    image: pihole/pihole:latest
    container_name: pihole_secondary
    environment:
      - TZ=Europe/London
      - WEBPASSWORD=admin
    networks:
      pihole_net:
        ipv4_address: 192.168.8.242
    restart: unless-stopped
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80'

  unbound_primary:
    image: mvance/unbound:latest
    container_name: unbound_primary
    networks:
      pihole_net:
        ipv4_address: 192.168.8.241
    restart: unless-stopped

  unbound_secondary:
    image: mvance/unbound:latest
    container_name: unbound_secondary
    networks:
      pihole_net:
        ipv4_address: 192.168.8.242
    restart: unless-stopped

  keepalived:
    image: osinankur/keepalived:latest
    container_name: keepalived
    environment:
      - VIP=192.168.8.240
      - PRIMARY=192.168.8.241
      - SECONDARY=192.168.8.242
    networks:
      pihole_net:
        ipv4_address: 192.168.8.240
    restart: unless-stopped

networks:
  pihole_net:
    driver: bridge
